services:
  openwakeword:
    container_name: openwakeword
    build:
      context: .
      args:
        - WAKEWORD_MODEL_NAME=hey_jarvis
    devices:
      - "/dev/snd"
    restart: unless-stopped
    # volumes:
    #   - "./pipewire.conf.d:/home/appuser/.config/pipewire/pipewire.conf.d"
    environment:
      - AUTO_LINK_SOURCE=seed-microphone-mono
      - AUTO_LINK_TARGET=roc-sink
      - PUID=501
      - PGID=20
      - AUDIO_GID=29
    ports:
      - "10001:10001/udp"
      - "10002:10002/udp"
      - "10003:10003/udp"
      - "20001:20001/udp"
      - "20002:20002/udp"
      - "20003:20003/udp"
    stdin_open: true
    tty: true