services:
  wakeword:
    build:
      context: .
      args:
        - WAKEWORD_MODEL_NAME=hey_jarvis
    environment:
      - BASE_URL=192.168.1.16:9292
      - WAKEWORD_MODEL_NAME=hey_jarvis
      - WW_THRESHOLD=0.5
      - INFERENCE_FRAMEWORK=onnx
    devices:
      - /dev/snd
    restart: unless-stopped
    ports:
      - "8700:8700" # Push Notifications
    stdin_open: true
    tty: true