services:
  wakeword:
    build:
      context: .
      args:
        PUID: ${UID}
        PGID: ${GID}
        AUDIO_GID: ${AUDIO_GID}
        WAKEWORD_MODEL_NAME: hey_jarvis
    volumes:
      - /home/dave/.asoundrc:/etc/asound.conf
    environment:
      HA_HOST: ${HA_HOST}
      HA_PORT: ${HA_PORT}
      HA_TOKEN: ${HA_TOKEN}
      HA_SSL: ${HA_SSL}
      PUID: ${UID}
      PGID: ${GID}
      AUDIO_GID: ${AUDIO_GID}
    devices:
      - /dev/snd
    restart: unless-stopped
    group_add:   
      - ${AUDIO_GID}