services:
  wakeword:
    build:
      context: .
      args:
        PUID: ${UID}
        PGID: ${GID}
        AUDIO_GID: ${AUDIO_GID}
        WAKEWORD_MODEL_NAME: hey_jarvis
    # Optional
    volumes:
      - /home/dave/.asoundrc:/etc/asound.conf
    environment:
      HASS_TOKEN: ${HASS_TOKEN}
      CONFIG_PATH: ${CONFIG_PATH}
      PUID: ${UID}
      PGID: ${GID}
      AUDIO_GID: ${AUDIO_GID}
    devices:
      - /dev/snd
    restart: unless-stopped
    group_add:   
      - ${AUDIO_GID}