[project]
name = "wake-word-test"
version = "0.1.0"
description = "Open source voice assistant for your home"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "sounddevice==0.5.2",
    "pydub>=0.25.1",
    "pyaudio>=0.2.14",
    "openwakeword==0.6.0",
    "numpy>=1.26.4",
    "simpleaudio>=1.0.4",
    "wavio>=0.0.9",
    "websockets>=15.0.1",
]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[dependency-groups]
dev = [
    "ruff==0.11.11",
]
