[project]
name = "wake-word-test"
version = "0.1.0"
description = "Open source voice assistant for your home"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy<2.0.0",
    "openwakeword==0.6.0",
    "pulsectl>=24.12.0",
    "pydantic==2.11.7",
    "pyyaml==6.0.2",
    "scipy==1.15.3",
    "sounddevice==0.5.2",
    "pydub>=0.25.1",
    "pyaudio>=0.2.14",
]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[dependency-groups]
dev = [
    "ruff==0.11.11",
]
